### ISSUE TITLE
Numerical Gradient check for LSTM module fails 

### ISSUE THREAD

**Issue by jackevan1** [jcjohnson/torch-rnn#116]
Hi @jcjohnson 

First, thanks for sharing your codes.
When I run LSTM_test.lua couple of times, the gradcheck fails.
I was wondering is this something that you have observed as well? do have any idea why it happens? something with gradient calculation?
Here are some examples:

gradcheck
LE failed: 0.00010105305312325 > 0.0001

gradcheck
LE failed: 0.00011955874846904 > 0.0001

gradcheck
LE failed: 7.5370008748222e-05 > 1e-05

gradcheck
LE failed: 0.00090417234862281 > 1e-05

gradcheck
LE failed: 1.284068053429e-05 > 1e-05

Thanks

**Comment by jcjohnson** [comment]
The gradient check unit tests are nondeterministic since they generate random data; the gradient check thresholds are also pretty tight, so sometimes the gradient checks fail. Notice that most of the failures you post are just barely over the threshold, so I don't think you need to worry.

I should maybe make the unit tests deterministic by picking a fixed random seed.

**Comment by jackevan1** [comment]
Thanks for your reply. :)
I calculated the gradient of LSTM by myself as well and exactly got same thing as yours. Just asked here to make sure that I am not missing something here.
