### ISSUE TITLE
Sampling making sense text

### ISSUE THREAD

**Issue by PauloOgraddy** [jcjohnson/torch-rnn#146]
Hi,

I'm finding hard to create sentences which actually make sense, and more difficultly, paragraphs making sense as a whole. Most of the generated text looks non-sense to me. Has anyone cracked down this issue ? I'm feeling the key could be in having the right traning set.

Thanks

**Comment by robinsloan** [comment]
It's helpful to think of these RNNs as capturing the "flavor" of text rather than the meaning. Excellent output is nearly perfect in terms of spelling, grammar, and even style -- but there's no "there" there. Remember, the model is being trained to mimic the patterns whatever text it's given. It doesn't have anything to say, nor is it aware that text ever "says anything" at all.

It will require some significant advancements to the state of the art before we can generate text that coherently builds an argument, or a story, over many sentences and paragraphs.

In terms of getting the very best output within those constraints, though, I've found that things get really interesting and robust when you have 50MB+ of text. Which is a lot!

**Comment by AlekzNet** [comment]
@robinsloan  BTW, what model/parameters did you use for 50MB of text?

**Comment by robinsloan** [comment]
@AlekzNet Hey there: the computer with all my RNN stuff on it is currently in a box, in transit, but I will look this up when it's unpacked!

**Comment by AlekzNet** [comment]
@robinsloan  Thanks! Looking forward!

@PauloOgraddy What is the seq_length set up to?

**Comment by robinsloan** [comment]
@AlekzNet I tend to fiddle with my params a lot, but here's a representative sample that produced good results for me:

```
batch_size 1024
seq_length 128
rnn_size 1024
dropout 0.25
num_layers 2
learning_rate 2e-3
```

For me, the one thing that *never* helped was increasing `num_layers` beyond 2.

**Comment by AlekzNet** [comment]
So, you successfully used a NN with 13M parameters with 0.25 dropout for 50MB of text and you got reasonable output (e.g. logically consistent paragraphs)? Hmm... interesting... Do you remember what the training loss was? 

I tried to use a 5M network (512x3 no dropout) for 17MB text, but I could not make the loss lower than 1. 

Currently I'm training this net (24MB corpus): 

`batch_size 254 
seq_length 400
rnn_size 760
dropout 0.1
num_layers 3
learning_rate 1e-3`

I will try to use your model for the same data set.

**Comment by robinsloan** [comment]
@AlekzNet My loss tended to be ~1.1 for a wide variety of params, and also a wide variety of corpus sizes, from ~50MB to ~150MB. In fact, the only time it dropped below 1 was when I used a smaller corpus of around 20MB… and that model's generated text was, to me, quantitatively worse!

I think that's an important point: for me, loss is just a rough guide, and ultimately I judge models by their generated results. That's also why I tend to use a shorter `seq_length`: qualitatively (and intuitively) it seems to focus the RNN on spelling, grammar, style, and word choice, rather than inter-sentence structure, which (frankly) it won't ever be able to capture anyway -- at least not until the state of the art improves! (See my previous comment.)

**Comment by AlekzNet** [comment]
> I think that's an important point: for me, loss is just a rough guide, and ultimately I judge models by their generated results. 
Agree. This is the reason why I do not use validation, I validate it by myself.  And I prefer to not lose the data that can be used for training.

>That's also why I tend to use a shorter seq_length
My experiments with consequent texts (e.g. novels) showed that large windows (e.g. 2000) produce much better results. Currently I'm playing with dialogues, that usually have much less "consequent sense", so I use windows between 200 and 400. I calculated the distribution of the phrase length using Cornell dialogue movie database as an example:

![phrase-length-distribution](https://cloud.githubusercontent.com/assets/10780668/19832400/2049ef70-9e23-11e6-9f7a-923b559e26f5.png)

So the window length of 400 should cover most.

**Comment by brisker** [comment]
Hi, I follow the instructions but why the train.lua gives me this error?
jcc@jcc:~/torch-rnn$ th train.lua -input_h5 my_data.h5 -input_json my_data.json
Running with CUDA on GPU 0
/home/jcc/torch/install/bin/luajit: bad argument #2 to '?' (end index out of bound at /home/jcc/torch/pkg/torch/generic/Tensor.c:992)
stack traceback:
[C]: at 0x7f91bfdef4d0
[C]: in function '__index'
./util/DataLoader.lua:35: in function '__init'
/home/jcc/torch/install/share/lua/5.1/torch/init.lua:91: in function </home/jcc/torch/install/share/lua/5.1/torch/init.lua:87>
[C]: in function 'DataLoader'
train.lua:76: in main chunk
[C]: in function 'dofile'
.../jcc/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
[C]: at 0x00406670
Help ?

**Comment by saippuakauppias** [comment]
@AlekzNet, @robinsloan, @PauloOgraddy, hi! It's been quite some time since your last posts. And I would like to clarify.

**You came to find the optimal settings for a large corpus of training (from 50MB) for English?**

I now train RNN on 75МБ reviews about movies from IMDb on the default parameters. I would be interested to spend together an experiment to improve the readability of the final result. I could put the source files and the final checkpoint. And we could try together to achieve the best results, to identify optimal parameters.

**What do you say? Would you be interested?**

/cc @jcjohnson

**Comment by AlekzNet** [comment]
Sure, good idea!  
My last attempt was 39MB corpus and the following parameters:
GRU: 1000x3
dropout: 0.1
batchnorm
batch_size: 398
seq_length: 300

The final train loss was around 0.92. I do not do validation. The rest you can see here: https://github.com/AlekzNet/rnn-chatbot

My next plan is to use the reddit database (see https://github.com/pender/chatbot-rnn ).

**Comment by AlekzNet** [comment]
Oh, yes, and every epoch I remove the first line or two from the beginning of the corpus, so the whole content slides across the seq_length windows.

**Comment by antihutka** [comment]
I'm using ~127MB of chat logs and these settings seem to work for me:
Grid GRU, rnn_size=1696, wordvec_size=640, num_layers=4
dropout=0.2
learning_rate=0.0004
lr_decay_factor=0.75, lr_decay_every=2
seq_length=256, batch_size=128
seq_offset=1 (shifts training data by seq_length/2 every other epoch)
40 epochs total, I doubled seq_length and halved batch_size every 10 epochs.

**Comment by AlekzNet** [comment]
Whoa... GridGRU 1696x4 = 139M parameters! It's bigger than your corpus!

**Comment by antihutka** [comment]
It's only 65M parameters. I tried different settings, but this gave me the best results so far. Validation loss is around 1.0544.

**Comment by AlekzNet** [comment]
With wordvec_size=1696 it will be 139M. As far as I remember, the original GridGRU implementation by guillitte required wordvec_size to be the same size as the model. But I see you've made a lot of changes. Interesting...

**Comment by antihutka** [comment]
That's correct. The original GridGRU implementation didn't require it, at least when I started using it, it was just a suggestion. I implemented some new features in it and I'm working on some optimizations, but I didn't change its basic functionality.

**Comment by AlekzNet** [comment]
Ah, OK, at least when I tried it I was getting errors for any wordvec_sizes less than the model size. Possibly I was doing something wrong... I will try your version - it's very interesting to compare.

**Comment by antihutka** [comment]
Alright. I will try to push another performance improvement later today/tomorrow, but my GPU machine is down, so I won't be able to test it.

**Comment by lord-alfred** [comment]
@AlekzNet @antihutka wow! 
Your skill is very high! After your message I realized that what I'm trying to just configure the settings - it is fundamentally not true.

You could tell about the following things:
1. Why don't you change val_frac and test_frac in preprocessing?
2. **How do you check the result?** English is not my primary language. I find it difficult to understand whether the neural network gave the result. You use some checking in the dictionaries/errors/break into tokens, so as not to degradation after another attempt of learning?
3. You use Grid GRU/GRU networks "Question-answer"? I teach network just to produce high quality results on the source data, at the moment I have spars headers ~200k articles with the Wall Street Journal. And cleared the data from "non-English" characters and various other symbols. It might be interesting to try to train your network on such input data to produce "generation of plausible news headline." If Yes - tell me, I'll post the text file with headers.
4. Which articles would you recommend a beginner (me) to understand what parameters need to change in order to achieve the best result?
5. Do I need to added the least train loss and how does it affect the outcome?
6. Whether I will try to test Grid GRU/GRU to generate text, not thinking that it will be a "Question-answer"?

**Comment by saippuakauppias** [comment]
@AlekzNet @antihutka wow! 
Your skill is very high! After your message I realized that what I'm trying to just configure the settings - it is fundamentally not true.

You could tell about the following things:
1. Why don't you change val_frac and test_frac in preprocessing?
2. **How do you check the result?** English is not my primary language. I find it difficult to understand whether the neural network gave the result. You use some checking in the dictionaries/errors/break into tokens, so as not to degradation after another attempt of learning?
3. You use Grid GRU/GRU networks "Question-answer"? I teach network just to produce high quality results on the source data, at the moment I have spars headers ~200k articles with the Wall Street Journal. And cleared the data from "non-English" characters and various other symbols. It might be interesting to try to train your network on such input data to produce "generation of plausible news headline." If Yes - tell me, I'll post the text file with headers.
4. Which articles would you recommend a beginner (me) to understand what parameters need to change in order to achieve the best result?
5. Do I need to added the least train loss and how does it affect the outcome?
6. Whether I will try to test Grid GRU/GRU to generate text, not thinking that it will be a "Question-answer"?

**Comment by saippuakauppias** [comment]
@AlekzNet @antihutka wow! 
Your skill is very high! After your messages I realized that what I'm trying to just configure the settings - it is fundamentally not true.

You could tell about the following things:
1. Why don't you change val_frac and test_frac in preprocessing?
2. **How do you check the result?** English is not my primary language. I find it difficult to understand whether the neural network gave the result. You use some checking in the dictionaries/errors/break into tokens, so as not to degradation after another attempt of learning?
3. You use Grid GRU/GRU networks "Question-answer"? I teach network just to produce high quality results on the source data, at the moment I have parsed ~200k titles articles with the Wall Street Journal. And cleared the data from "non-English" characters and various other symbols. It might be interesting to try to train your network on such input data to produce "generation of plausible news titles". If Yes - tell me, I'll post the text file with this titles.
4. Which articles would you recommend a beginner (me) to understand what parameters need to change in order to achieve the best result?
5. Do I need to added the least train loss and how does it affect the outcome?
6. Whether I will try to test Grid GRU/GRU to generate text, not thinking that it will be a "Question-answer"?



# // sorry to do that.. but I want to draw all to the problem how to choose the optimal parameters for training..

@PauloOgraddy @SeanNaren @4-x @abangdd @achadha0111 @achyudhk @afabbro @ageitgey @ahendy0 @ai-factory @AI42 @akangaziz @alasdairtran @alehander42 @alexandershoup @almaslovskis @andremoeller @andresvivancov @anoidgit @anokland @anthonylauzon @antihutka @anupamaray @arbdigital @arindambhattacharya @Arish813 @arnau @ashispapu @asurdina @awesome-archive @Balinus @belvo @bemoregt @berdon @berkandemirel @billzorn @binuscz @bmackattack @BoredBored @boweiliu @boyihu @breezedeus @brisker @bulam @ceberly @chagge @changcheng1987 @changqing @ChrisCummins @chubbymaggie @chunsj @cobuma @ColumbiaDVMM @complyue @crassrobot @crazydonkey200 @crazylyf @cutthroat @Darktex @datascibox @davidcelis @devinberg @dgcrouse @justinmrkva @Dorniwang @drakh @drzax @dusenberrymw @DylanAuty @egordienko @ein3108 @elbamos @eldarbabayev @elhomosiguiente @ericqh @Evgeny-B @fantine16 @feiyang-nottingham @feiyuhug @fejiso @feynmanliang @gcheron @gidariss @gjtjx @gokceneraslan @goliasz @gouxiayibu @gphuang @guillitte @gurusura @hal2001 @helennn @HeXingwei @higain @hitluobin @hjpwhu @hnkulkarni @hoangnguyen3892 @hojinyoo @hughperkins @i077 @iamalbert @iassael @ilovecv @imclab @ivanebel @ixtel @JackHopkins @JamesChuanggg @jameskyle @janniktock @jaydenso @jboys @jeiros @jhcmine @JianboTang @jillnotjack @JINGHSU @jithsjoy @jmrinaldi @joelself @jonathanlofgren @jpollack @jsaribeiro @JuliusKunze @jungikim @junhocho @justbuchanan @justinchiu @digideskio @JustinWenzhaoLi @JW-CHEN @jwyang @kalyanp @kdbanman @keepsimpler @ketranm @BinbinBian @KokeCacao @kylemcdonald @learningtitans @lijian8 @LiliMeng @liuyang1123 @LiyuanLucasLiu @llgeek @louissmit @LuZhenHuan @maraoz @masdude @mattbierner @mcr-ksh @miradel51 @mktal @ml-ai-nlp-ir @ml-lab @monolithpl @muhammadriz @mxer @MyOwnClone @nadavbh12 @nateGeorge @NFSCH4 @ngimel @nicolas-ivanov @nightbay @njordsir @Noah1989 @NorThanapon @notimesea @NoviaDroid @nslater @nunb @oaomly @obrianjunior @offbit @oldgil @omshanti @oneyanshi @opraveen @pankajmauryatimes @parety @parthraghav @patiencett @pbayer8 @Peratham @phecy @pierrebeauguitte @pombredanne @praneethbellamkonda @pranjaldaga @preethamsp @ps00k @psfoley @qinghuizhao @qinhongwei @qnix @Razied @reaction @recursiveMake @rillaha @rlabuguen @robinsloan @cgiogkarakis @evelynmitchell @jaronmoore @johndpope @kelu124 @mcwhittemore @OstrichProjects @panyang @ruotianluo @shawkinsl @softpunch @wanjinchang @wuntoguo @yulgolem @Rocknrenew @rohitrawat @root20 @rremani @rsarxiv @rtc-alex @ruguevara @ruizhaogit @rustch3n @SadeghMSalehi @SalemAmeen @sanket-patil @scatterbrain333 @Scitator @selvaggi @shaonaghosh @shaoxuan92 @sidec @skinscanner @smartynov @sohuren @solarbaby @solidaqua @soumith @lgazpio @spaceraccoon @spyatakov @squidszyd @ssokhey @stonedavid @sukiakiumo @SulemanKazi @sumotoy @sunilkgrao @teome @terrykong @thecerial @theclaymethod @TheodoreGalanos @thomwolf @tianlongwang @tinyloop @tisaconundrum2 @tmp6154 @seominlee @todn @tonyzhang1231 @Tr4c3d @tracy-Ming @scutzck033 @troubledjoe @tybxiaobao @UnforeseenOcean @urisavka @urish @vanpersie32 @vi @vode @vseledkin @vyraun @wantajob @wavelets @wenjianhugit @wjpjet @wltongxing @wrapperband @xcyan @xi-studio @XSell @xuyuwei @xwgeng @xxxxxxxx-dl @yanfenglee @yanxiaole @YerevaNN @yfliao @yongduek @ZhangXinNan @zhaowei8188127 @zhixinshu @zhmz90 @zhuth

**Comment by saippuakauppias** [comment]
Your skill is very high! After your messages I realized that what I'm trying to just configure the settings - it is fundamentally not true.

You could tell about the following things:
1. Why don't you change val_frac and test_frac in preprocessing?
2. **How do you check the result?** English is not my primary language. I find it difficult to understand whether the neural network gave the result. You use some checking in the dictionaries/errors/break into tokens, so as not to degradation after another attempt of learning?
3. You use Grid GRU/GRU networks "Question-answer"? I teach network just to produce high quality results on the source data, at the moment I have parsed ~200k titles articles with the Wall Street Journal. And cleared the data from "non-English" characters and various other symbols. It might be interesting to try to train your network on such input data to produce "generation of plausible news titles". If Yes - tell me, I'll post the text file with this titles.
4. Which articles would you recommend a beginner (me) to understand what parameters need to change in order to achieve the best result?
5. Do I need to added the least train loss and how does it affect the outcome?
6. Whether I will try to test Grid GRU/GRU to generate text, not thinking that it will be a "Question-answer"?



# // sorry to do that.. but I want to draw all to the problem how to choose the optimal parameters for training..


@chubbymaggie @chunsj @cobuma @ColumbiaDVMM @complyue @crassrobot @crazydonkey200 @crazylyf @cutthroat @Darktex @datascibox @davidcelis @devinberg @dgcrouse @justinmrkva @Dorniwang @drakh @drzax @dusenberrymw @DylanAuty @egordienko @ein3108 @elbamos @eldarbabayev @elhomosiguiente @ericqh @Evgeny-B @fantine16 @feiyang-nottingham @feiyuhug @fejiso @feynmanliang @gcheron @gidariss @gjtjx @gokceneraslan @goliasz @gouxiayibu @gphuang @guillitte @gurusura @hal2001 @helennn @HeXingwei @higain @hitluobin @hjpwhu @hnkulkarni @hoangnguyen3892 @hojinyoo @hughperkins @i077 @iamalbert @iassael @ilovecv @imclab @ivanebel @ixtel @JackHopkins @JamesChuanggg @jameskyle @janniktock @jaydenso @jboys @jeiros @jhcmine @JianboTang @jillnotjack @JINGHSU @jithsjoy @jmrinaldi @joelself @jonathanlofgren @jpollack @jsaribeiro @JuliusKunze @jungikim @junhocho @justbuchanan @justinchiu @digideskio @JustinWenzhaoLi @JW-CHEN @jwyang @kalyanp @kdbanman @keepsimpler @ketranm @BinbinBian @KokeCacao @kylemcdonald @learningtitans @lijian8 @LiliMeng @liuyang1123 @LiyuanLucasLiu @llgeek @louissmit @LuZhenHuan @maraoz @masdude @mattbierner @mcr-ksh @miradel51 @mktal @ml-ai-nlp-ir @ml-lab @monolithpl @muhammadriz @mxer @MyOwnClone @nadavbh12 @nateGeorge @NFSCH4 @ngimel @nicolas-ivanov @nightbay @njordsir @Noah1989 @NorThanapon @notimesea @NoviaDroid @nslater @nunb @oaomly @obrianjunior @offbit @oldgil @omshanti @oneyanshi @opraveen @pankajmauryatimes @parety @parthraghav @patiencett @pbayer8 @Peratham @phecy @pierrebeauguitte @pombredanne @praneethbellamkonda @pranjaldaga @preethamsp @ps00k @psfoley @qinghuizhao @qinhongwei @qnix @Razied @reaction @recursiveMake @rillaha @rlabuguen @robinsloan @cgiogkarakis @evelynmitchell @jaronmoore @johndpope @kelu124 @mcwhittemore @OstrichProjects @panyang @ruotianluo @shawkinsl @softpunch @wanjinchang @wuntoguo @yulgolem @Rocknrenew @rohitrawat @root20 @rremani @rsarxiv @rtc-alex @ruguevara @ruizhaogit @rustch3n @SadeghMSalehi @SalemAmeen @sanket-patil @scatterbrain333 @Scitator @selvaggi @shaonaghosh @shaoxuan92 @sidec @skinscanner @smartynov @sohuren @solarbaby @solidaqua @soumith @lgazpio @spaceraccoon @spyatakov @squidszyd @ssokhey @stonedavid @sukiakiumo @SulemanKazi @sumotoy @sunilkgrao @teome @terrykong @thecerial @theclaymethod @TheodoreGalanos @thomwolf @tianlongwang @tinyloop @tisaconundrum2 @tmp6154 @seominlee @todn @tonyzhang1231 @Tr4c3d @tracy-Ming @scutzck033 @troubledjoe @tybxiaobao @UnforeseenOcean @urisavka @urish @vanpersie32 @vi @vode @vseledkin @vyraun @wantajob @wavelets @wenjianhugit @wjpjet @wltongxing @wrapperband @xcyan @xi-studio @XSell @xuyuwei @xwgeng @xxxxxxxx-dl @yanfenglee @yanxiaole @YerevaNN @yfliao @yongduek @ZhangXinNan @zhaowei8188127 @zhixinshu @zhmz90 @zhuth

**Comment by saippuakauppias** [comment]
Your skill is very high! After your messages I realized that what I'm trying to just configure the settings - it is fundamentally not true.

You could tell about the following things:
1. Why don't you change val_frac and test_frac in preprocessing?
2. **How do you check the result?** English is not my primary language. I find it difficult to understand whether the neural network gave the result. You use some checking in the dictionaries/errors/break into tokens, so as not to degradation after another attempt of learning?
3. You use Grid GRU/GRU networks "Question-answer"? I teach network just to produce high quality results on the source data, at the moment I have parsed ~200k titles articles with the Wall Street Journal. And cleared the data from "non-English" characters and various other symbols. It might be interesting to try to train your network on such input data to produce "generation of plausible news titles". If Yes - tell me, I'll post the text file with this titles.
4. Which articles would you recommend a beginner (me) to understand what parameters need to change in order to achieve the best result?
5. Do I need to added the least train loss and how does it affect the outcome?
6. Whether I will try to test Grid GRU/GRU to generate text, not thinking that it will be a "Question-answer"?



# // sorry to do that.. but I want to draw all to the problem how to choose the optimal parameters for training..


@hughperkins @i077 @iamalbert @iassael @ilovecv @imclab @ivanebel @ixtel @JackHopkins @JamesChuanggg @jameskyle @janniktock @jaydenso @jboys @jeiros @jhcmine @JianboTang @jillnotjack @JINGHSU @jithsjoy @jmrinaldi @joelself @jonathanlofgren @jpollack @jsaribeiro @JuliusKunze @jungikim @junhocho @justbuchanan @justinchiu @digideskio @JustinWenzhaoLi @JW-CHEN @jwyang @kalyanp @kdbanman @keepsimpler @ketranm @BinbinBian @KokeCacao @kylemcdonald @learningtitans @lijian8 @LiliMeng @liuyang1123 @LiyuanLucasLiu @llgeek @louissmit @LuZhenHuan @maraoz @masdude @mattbierner @mcr-ksh @miradel51 @mktal @ml-ai-nlp-ir @ml-lab @monolithpl @muhammadriz @mxer @MyOwnClone @nadavbh12 @nateGeorge @NFSCH4 @ngimel @nicolas-ivanov @nightbay @njordsir @Noah1989 @NorThanapon @notimesea @NoviaDroid @nslater @nunb @oaomly @obrianjunior @offbit @oldgil @omshanti @oneyanshi @opraveen @pankajmauryatimes @parety @parthraghav @patiencett @pbayer8 @Peratham @phecy @pierrebeauguitte @pombredanne @praneethbellamkonda @pranjaldaga @preethamsp @ps00k @psfoley @qinghuizhao @qinhongwei @qnix @Razied @reaction @recursiveMake @rillaha @rlabuguen @robinsloan @cgiogkarakis @evelynmitchell @jaronmoore @johndpope @kelu124 @mcwhittemore @OstrichProjects @panyang @ruotianluo @shawkinsl @softpunch @wanjinchang @wuntoguo @yulgolem @Rocknrenew @rohitrawat @root20 @rremani @rsarxiv @rtc-alex @ruguevara @ruizhaogit @rustch3n @SadeghMSalehi @SalemAmeen @sanket-patil @scatterbrain333 @Scitator @selvaggi @shaonaghosh @shaoxuan92 @sidec @skinscanner @smartynov @sohuren @solarbaby @solidaqua @soumith @lgazpio @spaceraccoon @spyatakov @squidszyd @ssokhey @stonedavid @sukiakiumo @SulemanKazi @sumotoy @sunilkgrao @teome @terrykong @thecerial @theclaymethod @TheodoreGalanos @thomwolf @tianlongwang @tinyloop @tisaconundrum2 @tmp6154 @seominlee @todn @tonyzhang1231 @Tr4c3d @tracy-Ming @scutzck033 @troubledjoe @tybxiaobao @UnforeseenOcean @urisavka @urish @vanpersie32 @vi @vode @vseledkin @vyraun @wantajob @wavelets @wenjianhugit @wjpjet @wltongxing @wrapperband @xcyan @xi-studio @XSell @xuyuwei @xwgeng @xxxxxxxx-dl @yanfenglee @yanxiaole @YerevaNN @yfliao @yongduek @ZhangXinNan @zhaowei8188127 @zhixinshu @zhmz90 @zhuth

**Comment by saippuakauppias** [comment]
Your skill is very high! After your messages I realized that what I'm trying to just configure the settings - it is fundamentally not true.

You could tell about the following things:
1. Why don't you change val_frac and test_frac in preprocessing?
2. **How do you check the result?** English is not my primary language. I find it difficult to understand whether the neural network gave the result. You use some checking in the dictionaries/errors/break into tokens, so as not to degradation after another attempt of learning?
3. You use Grid GRU/GRU networks "Question-answer"? I teach network just to produce high quality results on the source data, at the moment I have parsed ~200k titles articles with the Wall Street Journal. And cleared the data from "non-English" characters and various other symbols. It might be interesting to try to train your network on such input data to produce "generation of plausible news titles". If Yes - tell me, I'll post the text file with this titles.
4. Which articles would you recommend a beginner (me) to understand what parameters need to change in order to achieve the best result?
5. Do I need to added the least train loss and how does it affect the outcome?
6. Whether I will try to test Grid GRU/GRU to generate text, not thinking that it will be a "Question-answer"?



# // sorry to do that.. but I want to draw all to the problem how to choose the optimal parameters for training..


@masdude @mattbierner @mcr-ksh @miradel51 @mktal @ml-ai-nlp-ir @ml-lab @monolithpl @muhammadriz @mxer @MyOwnClone @nadavbh12 @nateGeorge @NFSCH4 @ngimel @nicolas-ivanov @nightbay @njordsir @Noah1989 @NorThanapon @notimesea @NoviaDroid @nslater @nunb @oaomly @obrianjunior @offbit @oldgil @omshanti @oneyanshi @opraveen @pankajmauryatimes @parety @parthraghav @patiencett @pbayer8 @Peratham @phecy @pierrebeauguitte @pombredanne @praneethbellamkonda @pranjaldaga @preethamsp @ps00k @psfoley @qinghuizhao @qinhongwei @qnix @Razied @reaction @recursiveMake @rillaha @rlabuguen @robinsloan @cgiogkarakis @evelynmitchell @jaronmoore @johndpope @kelu124 @mcwhittemore @OstrichProjects @panyang @ruotianluo @shawkinsl @softpunch @wanjinchang @wuntoguo @yulgolem @Rocknrenew @rohitrawat @root20 @rremani @rsarxiv @rtc-alex @ruguevara @ruizhaogit @rustch3n @SadeghMSalehi @SalemAmeen @sanket-patil @scatterbrain333 @Scitator @selvaggi @shaonaghosh @shaoxuan92 @sidec @skinscanner @smartynov @sohuren @solarbaby @solidaqua @soumith @lgazpio @spaceraccoon @spyatakov @squidszyd @ssokhey @stonedavid @sukiakiumo @SulemanKazi @sumotoy @sunilkgrao @teome @terrykong @thecerial @theclaymethod @TheodoreGalanos @thomwolf @tianlongwang @tinyloop @tisaconundrum2 @tmp6154 @seominlee @todn @tonyzhang1231 @Tr4c3d @tracy-Ming @scutzck033 @troubledjoe @tybxiaobao @UnforeseenOcean @urisavka @urish @vanpersie32 @vi @vode @vseledkin @vyraun @wantajob @wavelets @wenjianhugit @wjpjet @wltongxing @wrapperband @xcyan @xi-studio @XSell @xuyuwei @xwgeng @xxxxxxxx-dl @yanfenglee @yanxiaole @YerevaNN @yfliao @yongduek @ZhangXinNan @zhaowei8188127 @zhixinshu @zhmz90 @zhuth

**Comment by saippuakauppias** [comment]
Your skill is very high! After your messages I realized that what I'm trying to just configure the settings - it is fundamentally not true.

You could tell about the following things:
1. Why don't you change val_frac and test_frac in preprocessing?
2. **How do you check the result?** English is not my primary language. I find it difficult to understand whether the neural network gave the result. You use some checking in the dictionaries/errors/break into tokens, so as not to degradation after another attempt of learning?
3. You use Grid GRU/GRU networks "Question-answer"? I teach network just to produce high quality results on the source data, at the moment I have parsed ~200k titles articles with the Wall Street Journal. And cleared the data from "non-English" characters and various other symbols. It might be interesting to try to train your network on such input data to produce "generation of plausible news titles". If Yes - tell me, I'll post the text file with this titles.
4. Which articles would you recommend a beginner (me) to understand what parameters need to change in order to achieve the best result?
5. Do I need to added the least train loss and how does it affect the outcome?
6. Whether I will try to test Grid GRU/GRU to generate text, not thinking that it will be a "Question-answer"?



# // sorry to do that.. but I want to draw all to the problem how to choose the optimal parameters for training..


@recursiveMake @rillaha @rlabuguen @robinsloan @cgiogkarakis @evelynmitchell @jaronmoore @johndpope @kelu124 @mcwhittemore @OstrichProjects @panyang @ruotianluo @shawkinsl @softpunch @wanjinchang @wuntoguo @yulgolem @Rocknrenew @rohitrawat @root20 @rremani @rsarxiv @rtc-alex @ruguevara @ruizhaogit @rustch3n @SadeghMSalehi @SalemAmeen @sanket-patil @scatterbrain333 @Scitator @selvaggi @shaonaghosh @shaoxuan92 @sidec @skinscanner @smartynov @sohuren @solarbaby @solidaqua @soumith @lgazpio @spaceraccoon @spyatakov @squidszyd @ssokhey @stonedavid @sukiakiumo @SulemanKazi @sumotoy @sunilkgrao @teome @terrykong @thecerial @theclaymethod @TheodoreGalanos @thomwolf @tianlongwang @tinyloop @tisaconundrum2 @tmp6154 @seominlee @todn @tonyzhang1231 @Tr4c3d @tracy-Ming @scutzck033 @troubledjoe @tybxiaobao @UnforeseenOcean @urisavka @urish @vanpersie32 @vi @vode @vseledkin @vyraun @wantajob @wavelets @wenjianhugit @wjpjet @wltongxing @wrapperband @xcyan @xi-studio @XSell @xuyuwei @xwgeng @xxxxxxxx-dl @yanfenglee @yanxiaole @YerevaNN @yfliao @yongduek @ZhangXinNan @zhaowei8188127 @zhixinshu @zhmz90 @zhuth

**Comment by saippuakauppias** [comment]
Your skill is very high! After your messages I realized that what I'm trying to just configure the settings - it is fundamentally not true.

You could tell about the following things:
1. Why don't you change val_frac and test_frac in preprocessing?
2. **How do you check the result?** English is not my primary language. I find it difficult to understand whether the neural network gave the result. You use some checking in the dictionaries/errors/break into tokens, so as not to degradation after another attempt of learning?
3. You use Grid GRU/GRU networks "Question-answer"? I teach network just to produce high quality results on the source data, at the moment I have parsed ~200k titles articles with the Wall Street Journal. And cleared the data from "non-English" characters and various other symbols. It might be interesting to try to train your network on such input data to produce "generation of plausible news titles". If Yes - tell me, I'll post the text file with this titles.
4. Which articles would you recommend a beginner (me) to understand what parameters need to change in order to achieve the best result?
5. Do I need to added the least train loss and how does it affect the outcome?
6. Whether I will try to test Grid GRU/GRU to generate text, not thinking that it will be a "Question-answer"?



# // sorry to do that.. but I want to draw all to the problem how to choose the optimal parameters for training..


@sumotoy @sunilkgrao @teome @terrykong @thecerial @theclaymethod @TheodoreGalanos @thomwolf @tianlongwang @tinyloop @tisaconundrum2 @tmp6154 @seominlee @todn @tonyzhang1231 @Tr4c3d @tracy-Ming @scutzck033 @troubledjoe @tybxiaobao @UnforeseenOcean @urisavka @urish @vanpersie32 @vi @vode @vseledkin @vyraun @wantajob @wavelets @wenjianhugit @wjpjet @wltongxing @wrapperband @xcyan @xi-studio @XSell @xuyuwei @xwgeng @xxxxxxxx-dl @yanfenglee @yanxiaole @YerevaNN @yfliao @yongduek @ZhangXinNan @zhaowei8188127 @zhixinshu @zhmz90 @zhuth

**Comment by ChrisCummins** [comment]
@saippuakauppias please do not spam '@' references and then edit your comment to hide it.

**Comment by pombredanne** [comment]
for the posterity if you were spammed @ by @saippuakauppias https://twitter.com/pombr/status/838017330189844480

**Comment by lord-alfred** [comment]
Sorry, guys), But this repository can already be considered dead, as has long been no new commits and issues. And learn important things is unrealistic. Yes, I used a bad method to attract your attention. But maybe it will give some results.

**Comment by saippuakauppias** [comment]
Sorry, guys), But this repository can already be considered dead, as has long been no new commits and issues. And learn important things is unrealistic. Yes, I used a bad method to attract your attention. But maybe it will give some results.

**Comment by davidcelis** [comment]
@saippuakauppias Please do not do this ever again.

**Comment by dgcrouse** [comment]
@brisker, please stop posting unrelated comments in threads.

**Comment by dgcrouse** [comment]
This issue has gone out of control and off-topic, so I am closing it.
