### ISSUE TITLE
Nuance for setup: `sudo apt-get install -y python2.7-dev`

### ISSUE THREAD

**Issue by hughperkins** [jcjohnson/torch-rnn#2]
Hi Justin,

Slight nuance for setup: I think one needs to also do `sudo apt-get -y install python2.7-dev`, prior to running the `pip install` command.

Also, it failed with 'cant install numpy', so maybe need to reorder the requirements.txt file?  But I installed like this:

```
pip install Cython
pip install numpy
pip install -r requirements
```
(or perhaps re-order the requirements.txt file perhaps?  or file a bug report with 

I also needed to:
```
sudo apt-get install libhdf5-dev
```
...prior to installing the hdf5 luarocks.  I think?

**Comment by jcjohnson** [comment]
Thanks! You're right about needing python2.7-dev and libhdf5-dev; I added those to the installation section.

I might rewrite the preprocessing logic in Lua, serializing with torch rather than HDF5; that would get rid of the Python and HDF5 dependencies.

You're also right about the requirements.txt - installing from it in a fresh virtualenv failed for me too; I manually reordered it and it seems to work now.

That seems like a bug in pip; `pip freeze` puts h5py before numpy, even though [the h5py setup.py](https://github.com/h5py/h5py/blob/master/setup.py) seems to declare numpy as a dependency.

**Comment by hughperkins** [comment]
Ok. The hdf5 bit is just because you are using python?

**Comment by jcjohnson** [comment]
I really like HDF5 - it's easy to read and write from just about any language, and it's pretty efficient in terms of file size. For most projects my pipeline has been to preprocess data with Python, dump to HDF5, read HDF5 from Lua to train models, dump results to JSON, and run analysis in Python.

For the purposes of this project, torch serialization would work fine; I just went for my standard approach out of habit.
