### ISSUE TITLE
documentation on how the faster and memory-efficient results are achieved

### ISSUE THREAD

**Issue by blackyang** [jcjohnson/torch-rnn#76]
@jcjohnson thanks for sharing your work! 

Is there any documentations on how the faster and memory-efficient results are achieved? I read #60  and it seems that you did something special for clones. Could you further explain it? Thanks. I can also take a look at the code to figure it out.

**Comment by nicholas-leonard** [comment]
@blackyang I think I can answer this. Basically, instead of implementing LSTMs using a bunch of existing modules, @jcjohnson implemented to forward and backward methods using BLAS directly. This bypasses the need for a bunch of intermediate buffers inherent to using Modules (which each have their own). 

So when you use modules to implement time-steps, each time-step is a clone of that module with shared parameters. In @jcjohnson's code, he doesn't even need to clone any modules because their is only one module that manages the looping through time-steps. This also makes the code much simpler.

**Comment by windweller** [comment]
Can you be slightly more elaborate on how he manages to use BLAS directly? Maybe because I'm very new to Lua/Torch, I don't see any specific BLAS wrapper or import in the code....

**Comment by jcjohnson** [comment]
Thanks @nicholas-leonard for the explanation!

@windweller Torch essentially has two levels of abstraction: It has Tensors (multidimensional arrays) and a bunch of methods for efficiently operating on Tensors, such as elementwise operations, matrix multiplications, etc; you can find a full list in  [tensor.md](https://github.com/torch/torch7/blob/master/doc/tensor.md) and [maths.md](https://github.com/torch/torch7/blob/master/doc/maths.md). Many of these operations use BLAS to operate efficiently. At this level Torch looks a lot like numpy; it is a general library for scientific computing, without a lot of stuff specific to neural nets.

The other layer in Torch is the neural net layer, as seen in the nn package. This package uses the Tensor abstraction to implement a bunch of Modules; each module knows how to perform a forward and backward computation, and they can be composed to build complex neural nets.

At the neural net layer, there are basically two ways to build new operations. One way is to compose existing modules to perform a more complex computation (like an LSTM); this is usually pretty quick to develop because you don't have to worry about implementing the backward pass yourself. As with many software systems, this modularity comes at a price: for complex computations (like an LSTM), composing them out of many modules makes development quick, but can be inefficient since each module stores both its output and the gradient of its input.

In torch-rnn I've taken a different approach, and explicitly implemented the LSTM forward and backward passes using Tensor methods rather than building out of existing modules. Once you look at the entire LSTM computation, it turns out that there are a lot of intermediate values in both the forward and backward pass that don't need to be explicitly stored; they can be computed, used, and then thrown away. Moreover, since all of this is done manually using Tensors, you can reuse the same buffers over and over again for these intermediates, which saves a ton of memory.

The other wrinkle has to do with clones. In Torch if you want to have multiple Modules share the same weights, you need to use a cloning mechanism; this can be somewhat brittle and annoying to work with. Since torch-rnn manually implements the forward and backward pass for the entire timeseries, there is no need for explicit cloning: all gradients with respect to the recurrent weight matrices are summed manually.

Overall this approach leads to much more efficient code, but the downside is that you have to start from scratch every time you want to implement a new type of recurrence (RNN, LSTM, GRU, etc). However at this point an LSTM is a pretty well-established building block, so I thought it was worth the effort to write an efficient one.
